export const docs = {
  navigation: [
    {
      title: 'Global',
      links: [
        {title: 'Introduction', href: '/'},
        {title: 'Getting started', href: '/getting-started'},
        {title: 'Utilities', href: '/utilities'},
        {title: 'Layout', href: '/layout'},
        {title: 'Typography', href: '/typography'},
      ],
    },
    {
      title: 'Layout',
      links: [
        {title: 'Container', href: '/container'},
        {title: 'Grid', href: '/grid'},
        {title: 'Section', href: '/section'},
      ],
    },
    {
      title: 'Form Elements',
      links: [
        {title: 'Checkbox', href: '/checkbox'},
        {title: 'Select', href: '/select'},
        {title: 'DatePicker', href: '/date-picker'},
        {title: 'Input', href: '/input'},
        {title: 'Multi Email', href: '/multi-email'},
        {title: 'Multi Select', href: '/multi-select'},
        {title: 'Radio Group', href: '/radio-group'},
        {title: 'Slider', href: '/slider'},
        {title: 'Switch', href: '/switch'},
        {title: 'Timepicker', href: '/timepicker'},
        {title: 'Toggle', href: '/toggle'},
      ],
    },
    {
      title: 'Buttons',
      links: [
        {title: 'Button', href: '/button'},
        {title: 'DoubleLabelLink', href: '/double-label-link'},
        {title: 'Link', href: '/link'},
      ],
    },
    {
      title: 'Other',
      links: [
        {title: 'Accordion', href: '/accordion'},
        {title: 'Alert Dialog', href: '/alert-dialog'},
        {title: 'Alert', href: '/alert'},
        {title: 'Aspect Ratio', href: '/aspect-ratio'},
        {title: 'Avatar', href: '/avatar'},
        {title: 'Badge', href: '/badge'},
        {title: 'Calendar', href: '/calendar'},
        {title: 'Card', href: '/card'},
        {title: 'Collapsible', href: '/collapsible'},
        {title: 'Command', href: '/command'},
        {title: 'Dialog', href: '/dialog'},
        {title: 'Drawer', href: '/drawer'},
        {title: 'DropdownMenu', href: '/dropdown-menu'},
        {title: 'HoverCard', href: '/hover-card'},
        {title: 'NavigationList', href: '/navigation-list'},
        {title: 'ProgressiveImage', href: '/progressive-image'},
        {title: 'Popover', href: '/popover'},
        {title: 'ScrollArea', href: '/scroll-area'},
        {title: 'Sheet', href: '/sheet'},
        {title: 'Skeleton', href: '/skeleton'},
        {title: 'Steps', href: '/steps'},
        {title: 'Table', href: '/table'},
        {title: 'Tabs', href: '/tabs'},
        {title: 'Toast', href: '/toast'},
        {title: 'Tooltip', href: '/tooltip'},
      ],
    },
  ],
}
