name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version-file: '.nvmrc'

    - name: Install turbo
      shell: bash
      run: npm i -g turbo

    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

    - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      name: pnpm-cache
      id: pnpm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Cache TypeScript TSBuild Info Files
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: '*/*/node_modules/.cache/tsbuildinfo.json'
        # Commit hash is for working around this: https://github.com/actions/cache/issues/106
        key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

    - name: pnpm
      shell: bash
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile --prefer-offline
