name: 'Deploy'

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy Docs'

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: '.nvmrc'

      - name: Install Vercel CLI
        run: npm install --global vercel@59.25.0

      - name: Deploy to Production
        run: vercel deploy --prod --yes --token="$VERCEL_TOKEN"
