name: 'Deploy'

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy Docs'

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: ⎔ Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: 'Deploy to Vercel'
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
