name: 'Deploy'

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy Docs'

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: '.nvmrc'

      - name: Install Vercel CLI
        run: npm install --global vercel@59.25.0

      - name: Deploy to Production
        run: vercel deploy --prod --yes --token="$VERCEL_TOKEN"
